export const ErrorCodes = {
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RENDER_ERROR: 'RENDER_ERROR',
  PDF_CONVERSION_ERROR: 'PDF_CONVERSION_ERROR',
  EMAIL_SEND_ERROR: 'EMAIL_SEND_ERROR',
  AGGREGATION_ERROR: 'AGGREGATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
